### ISSUE TITLE
please translate the README into english

### ISSUE THREAD

**Issue by rubo77** [ninuxorg/openwrt-basilicata#5]
In German Freifunk, we set up all scripts in english, so the international work is much easyer.

please translate it into inglish (use google translate for a start) and move the italian documentation into README_it.md

**Comment by nemesifier** [comment]
Hi @rubo77, after writing these scripts, I realised the bash approach is very limited.
I have recently rewritten the procedure in an ansible-role, which much more configurable and well documented (in english):
https://github.com/openwisp/ansible-openwisp2-imagegenerator

Since I consider this approach obsolete, I don't plan to work a anymore on this repo. I will keep improving [ansible-openwisp2-imagegenerator](https://github.com/openwisp/ansible-openwisp2-imagegenerator) instead.

I am also willing to make *ansible-openwisp2-imagegenerator* agnostic and rename it to *ansible-openwrt-imagegenerator* if other people are interested in using it and contributing to it.

**Comment by nemesifier** [comment]
Closed by 0e406cf
